### ISSUE TITLE
Unfortunately, my controllers still vibrate

### ISSUE THREAD

**Issue by Bamux** [Solla/VRControllerVibrationDisabler#1]
Does your program also support the Oculus Touch controllers of the Rift Cv1? I tried it today with the game Zenith, unfortunately my controllers still vibrate.

**Comment by Solla** [comment]
It's weird. Did you try this program on any other VR games?

The program is based on SteamVR, so the program only supports games based on SteamVR.

If you purchase the game on [Oculus Rift Store](https://www.oculus.com/experiences/quest/3594982710558708), please check that the game is running based on SteamVR.

**Comment by Bamux** [comment]
I use the Steam version of the game. I also tested In Death and Eleven Table Tennis, in both games the controller still vibrates.
When I start VibrationDisable.exe, the following message appears.
![image](https://user-images.githubusercontent.com/18372137/152706961-00aa60ab-cdde-465a-a48e-d1cf90cb38b9.png)

**Comment by Solla** [comment]
It seems that the program is working normally. I don't know what's going on.

I guess that my program has some compatible issues in Rift Cv1.
Unfortunately, since I don't have Rift Cv1, I couldn't provide any technical supports right now.

**Comment by Bamux** [comment]
Thanks for the quick reply. Too bad, you were my last hope. It's so annoying that disabling vibrations is not adjustable by default in every game or globally in the driver.

**Comment by Solla** [comment]
The issue has been resolved. I forgot to add the configuration files of Oculus Touch Controller.

Now the program supports HTC Vive Controller, Valve Index Controller, Oculus Touch Controller, HTC Vive Cosmos Controller and Holographic Controller.

**Comment by Bamux** [comment]
Great, it works for me now. Unfortunately, the performance seems to suffer significantly from the program. Zenith no longer runs consistently at 90 FPS. As soon as I quit the program (VibrationDisable.exe), everything runs smoothly again. Do you have any idea what this could be?

**Comment by Solla** [comment]
I think the performance issue was caused by the bad QoS policy of data transmission. Have you tried to use USB-C to connect your HMD?

I've made some modifications to reduce the amount of data transmitted. However, it might impair the performance of my program. You might still feel gentle rumbles even if the program is on. 
If you are using wireless transmission, you can give it a try.

**Comment by Bamux** [comment]
I tried the new release and the performance problems seem to be fixed, but unfortunately my controller vibrates again audibly for most things. Unfortunately, I don't have an adapter to connect my Rift Cv1 to a USB-C port.

**Comment by Solla** [comment]
My implementation requires a stable connection and sufficient bandwidth. 

I tried to increase the data transfer rate of my program. A higher data transfer rate can reduce the vibrotactile force that you feel.
However, it might be harmful for game performance.
You can download the binary files and use them to replace _VibrationDisable.exe_. 
You can also compile the entire project yourself. Just modify the _MAX_FPS_ in _VibrationDisable\Program.cs_.

If the solution helps, I will write a config file for users to decide data rate themselves.

[VRControllerVibrationDisabler_250Hz_500Hz.zip](https://github.com/Solla/VRControllerVibrationDisabler/files/8090188/VRControllerVibrationDisabler_250Hz_500Hz.zip)

**Comment by Bamux** [comment]
I have tried both variants (250Hz and 500Hz) and both work great. Almost all vibrations filtered out. A few vibrations still come through, e.g. when climbing a wall, but that is completely okay.
I also didn't notice any frame drops anymore.
